### ISSUE TITLE
Add Swift 4.x support

### ISSUE THREAD

**Issue by twodayslate** [twodayslate/SplitView#5]
Support Swift 4.2 at least

**Comment by subdan** [comment]
I see that your project supports Swift 5.0. Close the issue.

**Comment by twodayslate** [comment]
My understanding was swift 5 project won’t work with older swift 4 projects. This is a low priority but I believe a lot of people still use swift 4.x no?

**Comment by twodayslate** [comment]
Builds fine with Swift 4.2
