### ISSUE TITLE
Use Reducers

### ISSUE THREAD

**Issue by twodayslate** [twodayslate/SplitView#6]
https://www.swiftbysundell.com/articles/reducers-in-swift/

https://github.com/twodayslate/SplitView/blob/master/splitview/SplitView.swift#L121-L131

**Comment by subdan** [comment]
Hello. I can update your code to use reducers. I will do it as a part of Hacktoberfest 2019. I will open Pull Request on October 1.

**Comment by twodayslate** [comment]
Looking forward to it
